language: go

go:
  - "1.12"

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -osarch="linux/amd64" -osarch="darwin/amd64" -osarch="windows/amd64" -osarch="linux/386" -osarch="darwin/386" -osarch="windows/386"
  - ghr --username mvmaasakkers --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
